name: TestPlugin
author: Atoman03
version: 0.1
api: [3.0.0-ALPHA11]
main: Atoman03\TestPlugin\Main
description: Heal and feed command

commands:
    test:
        description: Heal yourself
        usage: "/test <heal:feed>"
        permission: tt
permission:
    tt:
        default: OP
        descrition: Allows player to use /test
        children:
    tt.heal:
        default: OP
        description: Allows player to use /test heal
        children:
    tt.feed:
        default: OP
        description: Allows player to use /test feed
        children: